### ISSUE TITLE
Symfony2 firewall doesn't hook "check_path" and "logout" routes

### ISSUE THREAD

**Issue by giovkanata** [alexandresalome/multisite-bundle#7]
**For brevity I omitted the parts of not essential code.**

app/config/config.yml:
```
alex_multisite:
    default_branding: world_site
    default_locale:   %locale%
    brandings:
        _defaults:
            active: true
        world_site:
            en: { host: %domain_world_site% }
        admin_control_panel:
            _defaults:
                active: true
            en: { host: %domain_admin_control_panel% }
```
app/config/security.yml:
```
firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_control_panel:
            provider: administrators
            context: %domain_admin_control_panel%
            host: %domain_admin_control_panel%
            pattern: ^/
            anonymous: ~
            form_login:
                # Login paths:
                login_path: security_admin_login
                check_path: security_admin_login_check
                # Login success options
                always_use_default_target_path: true
                default_target_path: gp_admin_dashboard
                # Login failed options
                failure_path: security_admin_login
                # Login options
                username_parameter: email
                password_parameter: password
                # Remember me disabled on admin!
                remember_me: false
                # Token csrf options
                csrf_provider: form.csrf_provider
                csrf_parameter: _auth_token
            logout:
                # Logout paths
                path: security_admin_logout
                target: security_admin_login
                # Logout options
                invalidate_session: true # the authenticated session will be unavailable afterwards

    access_control:
        - { host: %domain_admin_control_panel%, path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { host: %domain_admin_control_panel%, path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { host: %domain_admin_control_panel%, path: ^/, roles: ROLE_ADMIN }
```
app/config/routing.yml:
```
gp_admin:
    resource: "@GpAdminBundle/Resources/config/routing.yml"
```
Resources/config/routing.yml:
```
gp_admin_dashboard:
    resource: "@GpAdminBundle/Controller/DashboardController.php"
    type: annotation

gp_admin_security:
    resource: "@GpAdminBundle/Controller/SecurityController.php"
    type: annotation
```
SecurityController:
```
use Alex\MultisiteBundle\Annotation\Route;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\SecurityContextInterface;


class SecurityController extends Controller
{
    /**
     * @Route(name="security_admin_login", paths={
     *   "admin_control_panel"={
     *     "en"="/login",
     *   },
     * })
     * @Method({"GET"})
     */
    public function loginAction(Request $request)
    {
        $session = $request->getSession();
        // errors verify
        if ($request->attributes->has(SecurityContextInterface::AUTHENTICATION_ERROR)) {
            $error = $request->attributes->get(SecurityContextInterface::AUTHENTICATION_ERROR);
        } elseif (null !== $session && $session->has(SecurityContextInterface::AUTHENTICATION_ERROR)) {
            $error = $session->get(SecurityContextInterface::AUTHENTICATION_ERROR);
            $session->remove(SecurityContextInterface::AUTHENTICATION_ERROR);
        } else {
            $error = '';
        }

        if ($error) {
            $error = $error->getMessage();
        }

        $csrfToken = $this->container->get('form.csrf_provider')->generateCsrfToken('authenticate');

        return $this->render('GpAdminBundle:Security:login.html.twig', array(
            'error' => $error,
            'csrf_token' => $csrfToken,
            )
        );
    }

    /**
     * @Route(name="security_admin_login_check", paths={
     *   "admin_control_panel"={
     *     "en"="/login_check",
     *   },
     * })
     * @Method({"POST"})
     */
    public function checkAction()
    {
        throw new \RuntimeException('Something wrong with firewall LOGIN_CHECK configuration.');
    }

    /**
     * @Route(name="security_admin_logout", paths={
     *   "admin_control_panel"={
     *     "en"="/logout",
     *   },
     * })
     * @Method({"GET"})
     */
    public function logoutAction()
    {
        throw new \RuntimeException('Something wrong with firewall LOGOUT configuration.');
    }
```
php app/console router:debug:
```
_i18n__admin_control_panel_en__security_admin_login    ANY    ANY    admin.youintent.local /login
_i18n__admin_control_panel_en__security_admin_login_check    ANY    ANY admin.youintent.local /login_check
_i18n__admin_control_panel_en__security_admin_logout    ANY    ANY admin.youintent.local /logout
_i18n__admin_control_panel_en__gp_admin_dashboard   ANY    ANY    admin.youintent.local /
```
Well, with this configuration the firewall behavior is like I wrote in the title and throws the controller exception.
If I use routes without annotations like this:
Resources/config/routing.yml:
```
gp_admin_dashboard:
    resource: "@GpAdminBundle/Controller/DashboardController.php"
    type: annotation

gp_admin_account:
    resource: "@GpAdminBundle/Controller/AccountController.php"
    type: annotation

#gp_admin_security:
#    resource: "@GpAdminBundle/Controller/SecurityController.php"
#    type: annotation

security_admin_login:
    path: /login
    host: admin.youintent.local
    defaults: { _controller: GpAdminBundle:Security:login }

security_admin_login_check:
    path: /login_check
    host: admin.youintent.local

security_admin_logout:
    path: /logout
    host: admin.youintent.local
```
php app/console router:debug change in:
```
security_admin_login    ANY    ANY    admin.youintent.local /login
security_admin_login_check    ANY    ANY admin.youintent.local /login_check
security_admin_logout    ANY    ANY admin.youintent.local /logout
_i18n__admin_control_panel_en__gp_admin_dashboard   ANY    ANY    admin.youintent.local /
```
the login process is ok and user is correctly authenticated but on redirect is thrown:
```
Unable to generate a URL for the named route "gp_admin_dashboard" as such route does not exist
```
from logs:
```
INFO - Matched route "security_admin_login_check" (parameters: "_route": "security_admin_login_check")
INFO - User "admin@admin.com" has been authenticated successfully
CRITICAL - Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "gp_admin_dashboard" as such route does not exist." at C:\xampp\htdocs\youintent\app\cache\dev\appDevUrlGenerator.php line 54 
Context: {"exception":"Object(Symfony\\Component\\Routing\\Exception\\RouteNotFoundException)"}
```
How can I resolve this issue premising that I would want localize and internationalize the login, logout and login_check routes, specially on my front-end subdomains?
It's possible to get it work with the annotations?
Any help will be really appreciate.
